This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./finalReport.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file finalReport.acn....done (44 entries accepted, 0 rejected).
Sorting entries....done (267 comparisons).
Generating output file finalReport.acr....done (110 lines written, 0 warnings).
Output written in finalReport.acr.
Transcript written in finalReport.alg.
